import 'package:pokemon_sleep_tools/data/models/models.dart';

/// Need set basic profile
List<PokemonProfile> getAllDemoProfiles() {
  final results = <PokemonProfile>[
    PokemonProfile(
      id: 1,
      basicProfileId: 18,
      character: PokemonCharacter.restrained,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.helpSpeedS,
      subSkillLv50: SubSkill.holdMaxS,
      subSkillLv75: SubSkill.dreamChipBonus,
      subSkillLv100: SubSkill.holdMaxM,
      ingredient2: Ingredient.i11,
      ingredientCount2: 2,
      ingredient3: Ingredient.i11,
      ingredientCount3: 3,
    ),
    PokemonProfile(
      id: 2,
      basicProfileId: 7,
      character: PokemonCharacter.c14,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.skillRateM,
      subSkillLv50: SubSkill.helpSpeedM,
      subSkillLv75: SubSkill.ingredientRateM,
      subSkillLv100: SubSkill.skillRateS,
      ingredient2: Ingredient.i8,
      ingredientCount2: 5,
      ingredient3: Ingredient.i8,
      ingredientCount3: 7,
    ),
    PokemonProfile(
      id: 3,
      basicProfileId: 47,
      character: PokemonCharacter.c17,
      subSkillLv10: SubSkill.holdMaxS,
      subSkillLv25: SubSkill.skillRateM,
      subSkillLv50: SubSkill.holdMaxM,
      subSkillLv75: SubSkill.helpSpeedS,
      subSkillLv100: SubSkill.skillLevelM,
      ingredient2: Ingredient.i2,
      ingredientCount2: 4,
      ingredient3: Ingredient.i2,
      ingredientCount3: 6,
    ),
    PokemonProfile(
      id: 4,
      basicProfileId: 20,
      character: PokemonCharacter.c25,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.skillRateS,
      subSkillLv50: SubSkill.helpSpeedS,
      subSkillLv75: SubSkill.holdMaxS,
      subSkillLv100: SubSkill.holdMaxS,
      ingredient2: Ingredient.i10,
      ingredientCount2: 2,
      ingredient3: Ingredient.i13,
      ingredientCount3: 2,
    ),
    PokemonProfile(
      id: 5,
      basicProfileId: 33,
      character: PokemonCharacter.c15,
      subSkillLv10: SubSkill.researchExpBonus,
      subSkillLv25: SubSkill.helpSpeedM,
      subSkillLv50: SubSkill.dreamChipBonus,
      subSkillLv75: SubSkill.ingredientRateM,
      subSkillLv100: SubSkill.holdMaxS,
      ingredient2: Ingredient.i4,
      ingredientCount2: 4,
      ingredient3: Ingredient.i12,
      ingredientCount3: 7,
    ),
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    basicProfileId: 36,
    // I/flutter (19740):    character: PokemonCharacter.c14,
    // I/flutter (19740):    subSkillLv10: SubSkill.holdMaxS,
    // I/flutter (19740):    subSkillLv25: SubSkill.helpSpeedS,
    // I/flutter (19740):    subSkillLv50: SubSkill.ingredientRateM,
    // I/flutter (19740):    subSkillLv75: SubSkill.skillRateS,
    // I/flutter (19740):    subSkillLv100: SubSkill.ingredientRateS,
    // I/flutter (19740):    ingredient2: Ingredient.i15,
    // I/flutter (19740):    ingredientCount2: 5,
    // I/flutter (19740):    ingredient3: Ingredient.i2,
    // I/flutter (19740):    ingredientCount3: 4,
    // I/flutter (19740): )
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    id: -1,
    // I/flutter (19740):    basicProfileId: 47,
    // I/flutter (19740):    character: PokemonCharacter.c15,
    // I/flutter (19740):    subSkillLv10: SubSkill.berryCountS,
    // I/flutter (19740):    subSkillLv25: SubSkill.skillLevelM,
    // I/flutter (19740):    subSkillLv50: SubSkill.holdMaxL,
    // I/flutter (19740):    subSkillLv75: SubSkill.researchExpBonus,
    // I/flutter (19740):    subSkillLv100: SubSkill.skillRateM,
    // I/flutter (19740):    ingredient2: Ingredient.i2,
    // I/flutter (19740):    ingredientCount2: 4,
    // I/flutter (19740):    ingredient3: Ingredient.i2,
    // I/flutter (19740):    ingredientCount3: 6,
    // I/flutter (19740): )
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    id: -1,
    // I/flutter (19740):    basicProfileId: 17,
    // I/flutter (19740):    character: PokemonCharacter.c15,
    // I/flutter (19740):    subSkillLv10: SubSkill.berryCountS,
    // I/flutter (19740):    subSkillLv25: SubSkill.skillLevelM,
    // I/flutter (19740):    subSkillLv50: SubSkill.holdMaxL,
    // I/flutter (19740):    subSkillLv75: SubSkill.researchExpBonus,
    // I/flutter (19740):    subSkillLv100: SubSkill.skillRateM,
    // I/flutter (19740):    ingredient2: Ingredient.i5,
    // I/flutter (19740):    ingredientCount2: 2,
    // I/flutter (19740):    ingredient3: Ingredient.i11,
    // I/flutter (19740):    ingredientCount3: 3,
    // I/flutter (19740): )
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    id: -1,
    // I/flutter (19740):    basicProfileId: 76,
    // I/flutter (19740):    character: PokemonCharacter.afraidLoneliness,
    // I/flutter (19740):    subSkillLv10: SubSkill.berryCountS,
    // I/flutter (19740):    subSkillLv25: SubSkill.skillRateM,
    // I/flutter (19740):    subSkillLv50: SubSkill.ingredientRateM,
    // I/flutter (19740):    subSkillLv75: SubSkill.ingredientRateS,
    // I/flutter (19740):    subSkillLv100: SubSkill.helpSpeedM,
    // I/flutter (19740):    ingredient2: Ingredient.i6,
    // I/flutter (19740):    ingredientCount2: 2,
    // I/flutter (19740):    ingredient3: Ingredient.i6,
    // I/flutter (19740):    ingredientCount3: 4,
    // I/flutter (19740): )
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    id: -1,
    // I/flutter (19740):    basicProfileId: 64,
    // I/flutter (19740):    character: PokemonCharacter.mischievous,
    // I/flutter (19740):    subSkillLv10: SubSkill.helpSpeedS,
    // I/flutter (19740):    subSkillLv25: SubSkill.researchExpBonus,
    // I/flutter (19740):    subSkillLv50: SubSkill.holdMaxS,
    // I/flutter (19740):    subSkillLv75: SubSkill.helpSpeedM,
    // I/flutter (19740):    subSkillLv100: SubSkill.skillLevelS,
    // I/flutter (19740):    ingredient2: Ingredient.i13,
    // I/flutter (19740):    ingredientCount2: 2,
    // I/flutter (19740):    ingredient3: Ingredient.i1,
    // I/flutter (19740):    ingredientCount3: 3,
    // I/flutter (19740): )
    // I/flutter (19740): PokemonProfile(
    // I/flutter (19740):    id: -1,
    // I/flutter (19740):    basicProfileId: 23,
    // I/flutter (19740):    character: PokemonCharacter.c12,
    // I/flutter (19740):    subSkillLv10: SubSkill.skillRateM,
    // I/flutter (19740):    subSkillLv25: SubSkill.helpSpeedS,
    // I/flutter (19740):    subSkillLv50: SubSkill.skillLevelS,
    // I/flutter (19740):    subSkillLv75: SubSkill.ingredientRateS,
    // I/flutter (19740):    subSkillLv100: SubSkill.ingredientRateM,
    // I/flutter (19740):    ingredient2: Ingredient.i12,
    // I/flutter (19740):    ingredientCount2: 5,
    // I/flutter (19740):    ingredient3: Ingredient.i12,
    // I/flutter (19740):    ingredientCount3: 7,
    // I/flutter (19740): )
    // D/EGL_emulation(19740): app_time_stats: avg=7.14ms min=1.01ms max=36.38ms count=52


  ];

  return results;
}