import 'package:pokemon_sleep_tools/data/models/models.dart';

/// Need set basic profile
List<PokemonProfile> getAllDemoProfiles() {
  final results = <PokemonProfile>[
    PokemonProfile(
      id: 1,
      basicProfileId: 18,
      character: PokemonCharacter.restrained,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.helpSpeedS,
      subSkillLv50: SubSkill.holdMaxS,
      subSkillLv75: SubSkill.dreamChipBonus,
      subSkillLv100: SubSkill.holdMaxM,
      ingredient2: Ingredient.i11,
      ingredientCount2: 2,
      ingredient3: Ingredient.i11,
      ingredientCount3: 3,
    ),
    PokemonProfile(
      id: 2,
      basicProfileId: 7,
      character: PokemonCharacter.c14,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.skillRateM,
      subSkillLv50: SubSkill.helpSpeedM,
      subSkillLv75: SubSkill.ingredientRateM,
      subSkillLv100: SubSkill.skillRateS,
      ingredient2: Ingredient.i8,
      ingredientCount2: 5,
      ingredient3: Ingredient.i8,
      ingredientCount3: 7,
    ),
    PokemonProfile(
      id: 3,
      basicProfileId: 47,
      character: PokemonCharacter.c17,
      subSkillLv10: SubSkill.holdMaxS,
      subSkillLv25: SubSkill.skillRateM,
      subSkillLv50: SubSkill.holdMaxM,
      subSkillLv75: SubSkill.helpSpeedS,
      subSkillLv100: SubSkill.skillLevelM,
      ingredient2: Ingredient.i2,
      ingredientCount2: 4,
      ingredient3: Ingredient.i2,
      ingredientCount3: 6,
    ),
    PokemonProfile(
      id: 4,
      basicProfileId: 20,
      character: PokemonCharacter.c25,
      subSkillLv10: SubSkill.ingredientRateS,
      subSkillLv25: SubSkill.skillRateS,
      subSkillLv50: SubSkill.helpSpeedS,
      subSkillLv75: SubSkill.holdMaxS,
      subSkillLv100: SubSkill.holdMaxS,
      ingredient2: Ingredient.i10,
      ingredientCount2: 2,
      ingredient3: Ingredient.i13,
      ingredientCount3: 2,
    ),
    PokemonProfile(
      id: 5,
      basicProfileId: 33,
      character: PokemonCharacter.c15,
      subSkillLv10: SubSkill.researchExpBonus,
      subSkillLv25: SubSkill.helpSpeedM,
      subSkillLv50: SubSkill.dreamChipBonus,
      subSkillLv75: SubSkill.ingredientRateM,
      subSkillLv100: SubSkill.holdMaxS,
      ingredient2: Ingredient.i4,
      ingredientCount2: 4,
      ingredient3: Ingredient.i12,
      ingredientCount3: 7,
    ),
  ];

  return results;
}